config/routes.rb
Portfolio::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :projects

  
  root :to => 'application#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  
  if Rails.env.production?
    devise :database_authenticatable,
           :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def index
    @projects = Project.order(:order_index).all
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(:order_index).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/_bio.html.erb
<div id="bio">
  <div>
    <h1>Scott Silverman</h1>
    <h2>Interaction Designer</h2>
  </div>
  <div>
    <p>
      I’m a San Francisco based interaction and UI designer who believes in simple and powerful products. I conceptualize, sketch, prototype, polish pixels, and write semantic markup. Take a peek at some of my work on <a href="http://dribbble.com/scottsil">Dribbble</a> or get in touch on <a href="http://twitter.com/scottsil">Twitter</a>.
    </p>
    <p>
      When not making software, I'm usually travelling, snapping photos, or skiing. I drink espresso daily and walk everywhere.
    </p>
  </div>
</div>

app/views/application/_projects.html.erb
<% if @projects.empty? %>
  No projects
  
<% else %>
  <ul class="projects" style="width: <%= Project.where(:display => true).count * 160 %>px;">
  <% @projects.each do |project| %>
  
    <% if project.order_index != nil %>
      <li class="project" <% if project.display == false %>style='display: none;' <% end %>>
        <% if project.video_id != nil %>
          <a class="vimeo" rel="<%= project.rel %>" href="http://player.vimeo.com/video/<%= project.video_id %>?title=0&amp;byline=0&amp;portrait=0" width="640" height="360" frameborder="0" webkitAllowFullScreen allowFullScreen title="<%= project.description %>" >
            <div class="title">
              <span><%= project.title %></span>
              <div class="arrow"></div>
            </div>
            <%= image_tag "/assets/project/#{project.title.downcase.gsub(/\s/, '')}/thumb.png" %>
          </a>
          
        <% else %>
          <a class="project" rel="<%= project.rel %>" href="assets/project/<%= project.title.downcase.gsub(/\s/, '') %>/full.png" title="<%= project.description %>" >
            <div class="title">
              <span><%= project.title %></span>
              <div class="arrow"></div>
            </div>
            <%= image_tag "/assets/project/#{project.title.downcase.gsub(/\s/, '')}/thumb.png" %>
          </a>
        <% end %>
        
      </li>
    <% end %>
  <% end %>
  </ul>
<% end %>

app/views/application/index.html.erb
<div id="container">
  <div id="bio-wrapper">
    <%= render :partial => "bio" %>
  </div>
  <div id="push"></div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- WHY, HEY THERE! Thanks for viewing source. I'm still learning, but strive to write clean, standards-compliant code and markup. This site is open source and under a Creative Commons Attribution 3.0 Unported License. Source code available at Github.com/scottsil/portfolio -->

  <title>Scott Silverman :: UI / Interaction Designer</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" >

  <!-- CSS: implied media=all -->
  <link href="/assets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <link href="/assets/print.css" media="print" rel="stylesheet" type="text/css" />
  <link href="/assets/fancybox/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" />
  <!-- end CSS-->
  <script type="text/javascript" src="http://use.typekit.com/udw0dpp.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-17722681-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>